### ISSUE TITLE
Trouble enabling Cypress Cloud with v13.1.0 and GHA v6.5.0

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/github-action#1024]
We have a [simple PR](https://github.com/muratkeremozcan/cypress-react-component-test-examples-with-vite/pull/3/files) no parallelization, just enabling recording on Cypress Cloud.

Running into `Resource not accessible by integration`.

https://github.com/muratkeremozcan/cypress-react-component-test-examples-with-vite/actions/runs/6123582978/job/16621800461

Perhaps Vite is also a factor, because Cypress GHA is used fine in the typecheck, lint and install jobs. 
But a combination of Vite, Cy Cloud and e2e/ct is the problem.

**Comment by MikeMcC399** [comment]
@muratkeremozcan 

- Check out also the closed issue https://github.com/cypress-io/github-action/issues/763, in case the comments there may help you.

**Comment by MikeMcC399** [comment]
@muratkeremozcan 

Have you resolved this issue? We're still waiting for your response.

**Comment by muratkeremozcan** [comment]
> @muratkeremozcan
> 
> Have you resolved this issue? We're still waiting for your response.

Bad link. Here we go.
https://github.com/muratkeremozcan/react-cypress-ts-vite-template

**Comment by muratkeremozcan** [comment]
> @muratkeremozcan
> 
> I don't see any bug in `github-action` in your workflow. I just see the error in Component testing:
> 
> `Error: error:0308010C:digital envelope routines::unsupported`
> 
> which is normally due to webpack not being compatible with Node.js `18` and later.
> 
> Your project uses `webpack@4.44.2`. You should make sure that your project runs locally under at least Node.js `18`. For that you would need to use `webpack@5`, however I see that this is a dependency of `react-scripts`, so I assume you will need to rework this part of your repo for compatibility.
> 
> Cypress no longer supports Node.js `16`. The lowest version still supported is Node.js `18`.
> 
> `cypress-io/github-action@v6` runs under `node20`. See [README > Compatibility](https://github.com/cypress-io/github-action/blob/master/README.md#compatibility).
> 
> Since this is a project issue, not a bug in `github-action` I suggest to close this issue.

I was hoping we can get away with node v16. It is fine for cy13, not for gha v6.

_Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with [Node 16's end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) schedule. It is recommended that users update to at least Node 18._


Thanks for the analysis. I will work on updating react scripts.

**Comment by MikeMcC399** [comment]
@muratkeremozcan 

Node.js `16` end-of-life was on Sep 11, 2023. Of course that does not mean that everything which previously worked with this version then stops working after this this day, but I would not expect any new fixes from Cypress for Node.js `16`. Cypress `13.x` does not block using it with Node.js `16`. I expect it might get blocked in a future Cypress `14.x` major version release, but that is just a guess.

The reason for the `cypress-io/github-action@v6` release is exactly to support `node20`, so if your project is not compatible with `node20` yet then you should not try to use `@v6`. If you want to continue with `node16` then use `cypress-io/github-action@v5` instead.

`cypress-io/github-action@v5` is now frozen and there will not be any new fixes for `cypress-io/github-action@v5`. This is because it is based on Node.js `16` and the fact that this version is in end-of-life status. See [Node.js release schedule](https://github.com/nodejs/release#release-schedule).
