### ISSUE TITLE
Make table title configurable or based on step name

### ISSUE THREAD

**Issue by alex1701c** [cypress-io/github-action#1050]
On one of my workflows, I run component and afterward E2E tests. The summary produces two tables with the identical heading "Cypress Results". I'd like to have the step name, a custom specified name or maybe just the hint if those are E2E/component tests in the table headers.

**Comment by MikeMcC399** [comment]
@alex1701c 

This enhancement would be nice to have!

The [example-chrome](https://github.com/cypress-io/github-action/actions/workflows/example-chrome.yml) workflow has two steps calling Cypress in one job and the results are not clear since only the job name, not the step names, is shown:

![image](https://github.com/cypress-io/github-action/assets/66998419/32e21e5a-7593-4ffa-8dfa-e586c8b1826b)

The first result summary is actually from the step `Chrome headless` and the second result summary is from the step `Chrome headed`.

The results summary is produced using `@actions/core` and the best description I found was on https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/.

I may have overlooked something, but I couldn't see any obvious way to add the step name into the summary. It may need an enhancement to  `@actions/core.summary` to add the step name.

**Comment by MikeMcC399** [comment]
@alex1701c 

The most flexible solution would be to introduce a parameter to override the default heading "Cypress Results" of the Job Summary. If there were implemented, then the above Job Summary could be changed for instance like this:

![example-chrome_after](https://github.com/cypress-io/github-action/assets/66998419/44d86761-1072-4377-b23f-241fd33cdd1a)

I plan to submit a PR to implement this suggestion.

**Comment by MikeMcC399** [comment]
- See PR https://github.com/cypress-io/github-action/pull/1056 for solution

**Comment by alex1701c** [comment]
>I may have overlooked something, but I couldn't see any obvious way to add the step name automatically into the summary. It may need an enhancement to @actions/core.summary to add the step name automatically.

I couldn't find one either.

**Comment by alex1701c** [comment]
Thanks a lot!
