### ISSUE TITLE
Pull docker image from Amazon ECR

### ISSUE THREAD

**Issue by h2oearth** [cypress-io/github-action#1090]
For anonymous users of Docker Hub, the rate limit is set to 100 pulls per 6 hours per IP address. This is an issue with large runners or runners that have static IPs. AWS ECR does not have this constraint. 

Could you please add the ability to use any given registry, like AWS ECR?

```
container:
      image: cypress/browsers: latest
      options: --user 1001
```

**Comment by MikeMcC399** [comment]
@h2oearth 

According to GitHub documentation [Defining the container image](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#defining-the-container-image):

> Use jobs.<job_id>.container.image to define the Docker image to use as the container to run the action. The value can be the Docker Hub image name or a registry name.

It sounds like what you are asking for is already available from GitHub Actions. Would you like to cross-check?

**Comment by MikeMcC399** [comment]
According to Cypress documentation [Continuous Integration > AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/aws-codebuild), Cypress Docker images are also available on the [Amazon Elastic Container Registry (ECR)](https://aws.amazon.com/ecr/) and can be found under https://gallery.ecr.aws/cypress-io.

These images can be used in Cypress GitHub Action workflows, for example:

```
    container:
      image: public.ecr.aws/cypress-io/cypress/browsers:latest
      options: --user 1001
```

Since the functionality being requested is already available, I will close this issue.
