### ISSUE TITLE
Ughh, cannot always pass ci-build-id

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#365]
After implementing #363 getting the following

<img width="729" alt="Screen Shot 2021-05-03 at 10 28 49 PM" src="https://user-images.githubusercontent.com/2212006/116954828-00c96000-ac5f-11eb-84cc-e282d3577e76.png">

We can only send ci-build-id if running in the parallel or group mode

**Comment by Andarist** [comment]
Shouldn't this restriction be lifted from Cypress itself? I know it will be hard to sync with this action right now as there are already versions of Cypress out there with this validation error in place. But putting that aside - since there is a need (GitHub Action case) to provide `--ci-build-id` to enable reruns, shouldn't the restriction be removed from the Cypress? If one gives it a `--ci-build-id` then just let it use it instead of requiring either `group` or `parallel`

**Comment by bahmutov** [comment]
Can you please explain though what is NOT working today, because I thought I understood the use case, but it seems I don't. For me, re-running the workflow always creates a new run just fine, no matter how it happens.

**Comment by Andarist** [comment]
We have used anoother CI provider before switching to GitHub Actions and we had our scripts defined in package.json. So when migrating to GitHub Actions we didn't really touch that setup a lot, we've only configured the workflow file to invoke the custom `command` from the `package.json`

In this situation, we didn't really provide any options specific to `cypress run` in the workflow file but rather we have kept them in that npm script which was already there. This had this slightly negative effect on us that the logic of this action here assumed that the custom `--ci-build-id` needs to be only computed when either `parallel` or `group` is given. But we had options like this in our npm script (custom `command`) and not in the actions options.

And without custom `--ci-build-id` Cypress has reached for available env variables to get that but, unfortunately, GitHub actions don't provide any env variable that would be unique to the run. You can only get the ID of the specific workflow execution but that isn't changed when one re-runs the workflow.

So we had to work around it by providing a custom `ciBuildId` that would contain a timestamp or smth else that would be unique. Or we could just move our options from the npm script to the workflow file. We have chosen the latter but I thought that it would be nice if this just would work out of the box because it's just a minor difference that doesn't look like it should influence ability to re-run.
