### ISSUE TITLE
"Cypress could not verify that this server is running"

### ISSUE THREAD

**Issue by crstauf** [cypress-io/github-action#535]
The server is running and accessible at the URL set in the `baseUrl` config property; what mechanism is used to test and verify availability?

**Comment by crstauf** [comment]
I found and reviewed cypress-io/cypress#3122: I’m not spinning up a local environment, it’s a website on the World Wide Web.

**Comment by crstauf** [comment]
Well how exciting, another GitHub repository that's unmaintained. 😞 👎

**Comment by tommytz** [comment]
I'm having the same problem :(

**Comment by MikeMcC399** [comment]
Closing, since this issue is stale and sorry for your experience. I wasn't involved at the time.

If there are still current problems then please submit a new issue with relevant details. Alternatively there is an active user community on
[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)
