### ISSUE TITLE
How to specify excludeSpecPattern per job?

### ISSUE THREAD

**Issue by sandinmyjoints** [cypress-io/github-action#575]
Latest version of Cypress action is sniping at me because I had `config: ignoreTestFiles=**/some glob` in one job in my workflow. 

```
The ignoreTestFiles configuration option is now invalid when set on the config object in Cypress version 10.0.0.
It is now renamed to excludeSpecPattern and configured separately as a testing type property: e2e.excludeSpecPattern
{
  e2e: {
    specPattern: '...',
  },
}
```

I don't want to add excludeSpecPattern to my cypress.config.js b/c I want to specify it only for one job, not all of them. I quickly tried it as a command line flag by doing

```diff
-          config: ignoreTestFiles=**/some glob
+          config: e2e.excludeSpecPattern=**/some glob
```

but that didn't work. Is there some other way I can specify it for only this job?

**Comment by kxm827** [comment]
Anyone ever figure this out?  I'm stuck on exactly this issue right now and can't find any docs around it.

**Comment by kxm827** [comment]
I found a way to get this to work.

```yml
          config: '{"e2e": { "excludeSpecPattern": "**/*visual*.cy.js" } }'
```

Basically you need to JSON.stringify the options you want to use.  Also, I had a hard time with this because I didn't expect to need the spec pattern to look within directories.  Without the leading `**/` it will not match anything.

This was a helpful tool for debugging the glob, which I found in the docs somewhere.

https://globster.xyz/?q=**%2F*visual*.cy.js&f=%2Fend-to-end-tests%2Fcypress%2Fe2e%2Flogin.cy.js%2C%2Fend-to-end-tests%2Fcypress%2Fe2e%2Fvisual.cy.js

**Comment by sandinmyjoints** [comment]
WFM! Thanks!
