### ISSUE TITLE
Poor browser performance when viewing logs in Github Actions 

### ISSUE THREAD

**Issue by tristanbes** [cypress-io/github-action#64]
Hello,

When viewing logs inside Github Actions for cypress, the page is very slow/unresponsive; (scrolling is lagging or freeze the scrolls for few secs)

Also, it's not related to you, but when having Github Refined extension, the tab is completely frozen/crashed (https://github.com/sindresorhus/refined-github/issues/2725).

Is this due to the huge "output log" that cypress generate ? or something else ?

Is there anything you can improve so the browser is not slowed down ?

environment: 
- Chrome (v79.0.3945.130)
- Macbook Pro 2019 
- 2,3Ghz Intel core i9
- 32Go RAM

![upgrade_JS_deps_by_tristanbes_·_Pull_Request__794_·_Yproximite_condictio](https://user-images.githubusercontent.com/346010/72813680-0ebec180-3c64-11ea-9f24-137a31541bac.png)

**Comment by bahmutov** [comment]
I am not sure what we can do on our side - the output is pretty minimal from Cypress side. I use GitHub refined and do not find GH Actions page terribly slow. I would suggest opening an issue or asking GitHub support about it. I suspect they create multiple Divs to render tool output there, rather than a single Div. If I can give an advice is to try looking at the test results in Cypress Dashbord 🤓

**Comment by tristanbes** [comment]
I've tested in private mode under chrome, it's not slow.

I suspect that LastPass extension is performing heavy DOM search looking for input login / input password for its helper; Sorry for the noise;
