### ISSUE TITLE
Is it possible to run both component + e2e tests (both w/ --parallel) in the same workflow?

### ISSUE THREAD

**Issue by franzwarning** [cypress-io/github-action#703]
Is there a good example of running both component and e2e tests in the same workflow? I have it working where I use parallel for e2e and NOT for component, but I'm wondering if there's a way to use parallel for both. Additionally, the cypress bot the comments on the PR is only commenting about the e2e tests, and not the component tests. Any ideas on what to do there? Thanks!

**Comment by MikeMcC399** [comment]
@franzwarning 

There hasn't been any response here to your questions. Are they still open or have you found answers in the meantime?

**Comment by noisy** [comment]
@franzwarning a month ago I was asking myself the same questions. At the end, I've decided to have 2 separate cypress configurations. 

This is how this looks in practice: https://github.com/noisy/portfolio/pull/104

![Uploading github.com_noisy_portfolio_pull_104.png…]()

checkout the cypress*.ts configs in main dfirectory: https://github.com/noisy/portfolio/tree/642c23e

and also github action configuration: https://github.com/noisy/portfolio/blob/642c23e/.github/workflows/cypress.yml

I'm linking to the 642c23e commit in my repository, because as for today, this is my latest commit on my master branch. I do not link to master branch in case if I will decide to change things in the future ;)

**Comment by MikeMcC399** [comment]
@noisy 

It looks like you are using two different action versions in the same workflow. That may not always work. Unless you need to pin the version due to a problem it's recommended to use just `@v5`. If you need to pin to a certain version like `@5.3.0` you should do that everywhere.

```
        uses: cypress-io/github-action@v5
        uses: cypress-io/github-action@v5.3.0
```

**Comment by noisy** [comment]
> It looks like you are using two different action versions in the same workflow. 

@MikeMcC399 thank for pointing that out. It was a mistake.

Personally, I always prefer to freeze a versions of all dependencies to be sure exactly on which version something was working.

**Comment by noisy** [comment]
> I've decided to have 2 separate cypress configurations.

BTW, it would be really nice if things like that would not be needed.

**Comment by MikeMcC399** [comment]
@noisy 

> > I've decided to have 2 separate cypress configurations.
> 
> BTW, it would be really nice if things like that would not be needed.

I'm not sure that it is necessary to have 2 separate Cypress configurations. That isn't specific to `github-actions` though. If you want to run this past the Cypress community on Discord any time. See https://discord.gg/cypress.
