### ISSUE TITLE
Add build & diff "/dist" folder workflow

### ISSUE THREAD

**Issue by jaffrepaul** [cypress-io/github-action#706]
Add workflow to [build & diff /dist folder](https://github.com/actions/javascript-action/blob/main/.github/workflows/check-dist.yml) on PR merges to avoid not triggering a build when this [step is missing](https://github.com/cypress-io/github-action/pull/621#issuecomment-1324762808)

**Comment by MikeMcC399** [comment]
@jaffrepaul 

It would be a good improvement to add this.

I have a few other suggestions for restructuring [main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) when you get to this point, like removing the redundant build with multiple node versions and taking the `markdown-link-check` out of the release flow.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Possibly this should be implemented together with branch protection rules. I don't have visibility into the rules, since I'm only a Contributor, but it seems that they are currently quite lax.

**Comment by jaffrepaul** [comment]
current master branch rules dictate: 
- branches must be up to date
- a PR & approval is required to merge
- status checks must pass

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/766 provides a suggested implementation to resolve this issue

I based a new workflow on the [workflow: check-dist.yml](https://github.com/actions/javascript-action/blob/main/.github/workflows/check-dist.yml) from the GitHub repo [actions/javascript-action](https://github.com/actions/javascript-action) as suggested by @jaffrepaul. [Create a JavaScript Action](https://github.com/actions/javascript-action) is provided as a template by GitHub to "bootstrap the creation of a JavaScript action".

I did not use the upload artifact part because I did not find it helpful. In the case of an error the Action log already shows the `git diff` output, which should be enough to be able to rectify the discrepancy. I also didn't use the `paths-ignore:` parameters, since it did not cover all cases and it would have been overly complicated to add them all. This means that the workflow may run when it is not strictly necessary, however the overhead is small and it makes the workflow easier to understand.

When the PR is merged it will signal to PR submitters that their PR is incomplete if they have changed [index.js](https://github.com/cypress-io/github-action/blob/master/index.js) without rebuilding the action.

The workflow will also signal a problem if bots such as `renovate` update dependencies embedded in [/dist/index.js](https://github.com/cypress-io/github-action/blob/master/dist/index.js) which would also require a rebuild.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

- Since https://github.com/cypress-io/github-action/pull/766 has now been merged, you could close your issue here

**Comment by jaffrepaul** [comment]
Done
