### ISSUE TITLE
[Configuration Request] Separate npm/yarn install from binary install 

### ISSUE THREAD

**Issue by trevorgerhardt** [cypress-io/github-action#79]
Within my workflow I have an initial [`install` step](https://github.com/conveyal/analysis-ui/blob/yarn-cache-workflow/.github/workflows/nodejs.yml#L10) that the other steps depend on. The step which contains the Cypress runner depends on that step, and restores the installed dependencies from the cache before running. Because the Cypress binary is not installed like traditional dependencies, I still [install the Cypress binary on each run](https://github.com/conveyal/analysis-ui/blob/yarn-cache-workflow/.github/workflows/nodejs.yml#L70). 

Ideally, I could turn off installing node dependencies separately from installing the cypress binary. It appears they are already separate functions combined into one step here: https://github.com/cypress-io/github-action/blob/master/index.js#L443

My proposal is to split the `install` configuration option into two options: `installDependencies` and `installCypressBinary`. That way I can control the `node_modules` cache manually, while the cypress github action can still control and cache the binary installation.

**Comment by bahmutov** [comment]
Hmm sounds good, maybe open a pull request?

**Comment by trevorgerhardt** [comment]
Will do 👍

**Comment by bahmutov** [comment]
Can you please give me the workflow file, so I better understand what and when you are trying to do. Is this the use case:

```
install NPM and cache dependencies yourself
(you don't need Cypress binary at all)
for example you could do
uses: @bahmutov/npm-install
env:
  CYPRESS_INSTALL_BINARY: 0
```

The above will install and cache NPM dependencies, but will skip Cypress binary download and unzip

Then down the line you want to run Cypress E2E tests. In that case, I suggest you run (since cypress NPM dependency has been installed already) `run: npx cypress install` and then cache the `~/.cache` folder yourself using `actions/cache`
