### ISSUE TITLE
Trying to run cypress test once received  deployment trigger from cypress 

### ISSUE THREAD

**Issue by virendra038** [cypress-io/github-action#859]
I have linked my repo with vercel account. Anytime i commit something it detects automatically and do the deployment.
In my github actions I want to listen for the vercel  deployment so that I can run my cypress tests against the updated code .
Can anyone share the steps how to do it ?

**Comment by MikeMcC399** [comment]
@virendra038 

I don't know if you will get an answer for your question here, as this is more of an error-reporting issue list.

There is however an active Discord user community, which you can access via the link https://discord.gg/cMjUZg7. You might find users with experience about your setup in the discussions.

**Comment by virendra038** [comment]
@MikeMcC399 
Can you help me with this ?

**Comment by MikeMcC399** [comment]
@virendra038 
> Can you help me with this ?

No, I can't really help you, since I don't have experience in your scenario. That is why I gave you the link to Discord.

GitHub Actions use event triggers to run. See [Triggering a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow). I suggest you read that documentation.

It seems you also asked the question in https://github.com/orgs/community/discussions/51562

**Comment by virendra038** [comment]
@MikeMcC399 
Thanks for the help. Do you know any github actions community on discord ?

**Comment by MikeMcC399** [comment]
@virendra038 

There is no special GitHub Actions community in the Cypress Community on Discord. There is a generic Help section.

**Comment by virendra038** [comment]
OK. 
Thanks for the help. 🤟 
@MikeMcC399

**Comment by nagash77** [comment]
Hi @virendra038 check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
