### ISSUE TITLE
Documentation request - update guide

### ISSUE THREAD

**Issue by tdevopsottawa** [cypress-io/github-action#931]
Like many other busy enterprise sysadmins in the world today, I'm going through hundreds of GHA workflows in my organization and replacing thousands of references to dozens of different github actions that all use the soon to be disabled, deprecated `set-output` command.

For you guys, you fixed the issue in v4.2.2 and newer.

However, I have a workflow using a very old version of your action: v2.

I'm not sure what might break if I upgrade from v2 to v4 or v5, and I don't really have the time to do a deep dive into how your action works as I have a huge number of these replacements on my plate and I can't really afford to dedicate the time.

Can someone add a short, sweet, "upgrade guide" for how to replace v2 or v3 with v5, what old parameters will break, etc. It would be massively appreciated by countless sysadmins around the world :)

**Comment by MikeMcC399** [comment]
@tdevopsottawa 

The answer to your question is summarized in the [README > Changelog](https://github.com/cypress-io/github-action/blob/master/README.md#changelog).

If you update `cypress-io/github-action@v2` to `cypress-io/github-action@v5` the action will run under `node16` (instead of `node12`). I'm not aware of any other parameters having breaking changes. Functionality has been added, and the only removals are the ones listed in the Changelog, which should not cause you any issue provided that your application is compatible with one of the currently supported versions of Node.js `16`, `18` and `20`.

**Comment by nagash77** [comment]
Hi @tdevopsottawa , issues in Cypress repos are reserved for bugs and feature requests.  As Mike suggested, I would point you to read through the changelog.  You can also check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions like this.
