### ISSUE TITLE
v5.8.2 causes a hang in running a chrome browser test. 

### ISSUE THREAD

**Issue by ssay-work** [cypress-io/github-action#941]
Our chrome browser tests started hanging on version 5.8.2 which was released on 6/13

```
Cypress package version: 12.13.0
Cypress binary version: 12.13.0
Electron version: 21.0.0
Bundled Node version: 16.16.0
```

Updating our action to v5.8.1 fixed our problem.

**Comment by ghiscoding** [comment]
I also have the same problem and using the previous version also works for me (thanks for that), it's probably caused by their last PR #914  
I was horrified to see that my CI was still running after 1 hour being hanged on this problem 😲 😱 

to add more info, here's my logs if it helps

```sh
Run cypress-io/github-action@v5
Received [13](https://github.com/ghiscoding/aurelia-slickgrid/actions/runs/5271867350/jobs/9533345209#step:13:14)0023424 of 159490239 (81.5%), 117.1 MBs/sec
Received 134217728 of 246805727 (54.4%), 125.0 MBs/sec
Received 159490239 of 159490239 (100.0%), 108.0 MBs/sec
Cache Size: ~152 MB (159490239 B)
/usr/bin/tar -xf /home/runner/work/_temp/874235dc-a472-4345-829e-2a510842b93d/cache.tzst -P -C /home/runner/work/aurelia-slickgrid/aurelia-slickgrid --use-compress-program unzstd
Received 246805727 of 246805727 (100.0%), 134.4 MBs/sec
Cache Size: ~235 MB (246805727 B)
/usr/bin/tar -xf /home/runner/work/_temp/b48efa7a-0495-4e37-bb5d-816ab923e5ba/cache.tzst -P -C /home/runner/work/aurelia-slickgrid/aurelia-slickgrid --use-compress-program unzstd
Cache restored successfully
Cache restored successfully
/usr/local/bin/yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.46s.
/usr/local/bin/yarn cypress cache list
yarn run v1.22.19
$ cypress open cache list

DevTools listening on ws://127.0.0.1:46553/devtools/browser/202a1e77-8ae1-4d05-9cc2-0b7c8fbe73f4
[2259:06[14](https://github.com/ghiscoding/aurelia-slickgrid/actions/runs/5271867350/jobs/9533345209#step:13:15)/[20](https://github.com/ghiscoding/aurelia-slickgrid/actions/runs/5271867350/jobs/9533345209#step:13:21)38[22](https://github.com/ghiscoding/aurelia-slickgrid/actions/runs/5271867350/jobs/9533345209#step:13:23).[28](https://github.com/ghiscoding/aurelia-slickgrid/actions/runs/5271867350/jobs/9533345209#step:13:29)8207:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
Error: The operation was canceled.
```
I cancelled it because it never stops, just hangs there until I cancel it

**Comment by MikeMcC399** [comment]
@ssay-work 

> Our chrome browser tests started hanging on version 5.8.2 which was released on 6/13

Please give more details about your workflow. If it's a public workflow you can give a link. If it's private, then you could post the workflow together with a log of the workflow run.

**Comment by MikeMcC399** [comment]
@ghiscoding

Looking at your logs I see that the workflow causing a problem is 
https://github.com/ghiscoding/aurelia-slickgrid/blob/master/.github/workflows/main.yml

Could you please confirm that I am looking at the right workflow?

There is an overlap in what this workflow does:

```
      - name: Run yarn install dependencies
        run: yarn --frozen-lockfile
```

will be repeated when `github-action` is called. When a `yarn.lock` file is found, then `yarn --frozen-lockfile` is executed.

```
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v5.8.1
```

Adding
```
  env:
    DEBUG: '@cypress/github-action'
```
should give more insight to what is happening. I will take a look in parallel at this.

**Comment by MikeMcC399** [comment]
@ssay-work / @ghiscoding

Thanks for both of you for your reports. I have submitted a PR to revert the change in `5.8.2` which caused problems for you.

**Comment by MikeMcC399** [comment]
@ghiscoding

The workflow
https://github.com/ghiscoding/aurelia-slickgrid/blob/master/.github/workflows/main.yml fails using
`cypress-io/github-action@v5.8.2` trying to execute the command
`/usr/local/bin/yarn cypress cache list`

The reason this fails is because [test/cypress/package.json](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/test/cypress/package.json) in your repo defines a script `cypress` which overrides the command `cypress`:

```json
"cypress": "cypress open"
```

so when `github-action` attempts to display the cypress cache content with

```bash
yarn cypress cache list
```

the command is executed instead as

```bash
yarn cypress open
```

So now the Cypress app (aka the launchpad) is opened and waits for user input, which never happens.

The example in the documentation on https://docs.cypress.io/guides/getting-started/opening-the-app#Adding-npm-Scripts suggests using a script name `cypress:open` for this purpose.

```json
{
  "scripts": {
    "cypress:open": "cypress open"
  }
}
```

I suggest that you follow this example, as defining a script `cypress` with the same name as the npm module `cypress` causes ambiguity for Yarn and should be avoided.

Previously the cache was being displayed using `npx cypress cache list` which always used the `cypress` command, however this did not work correctly for all types of Yarn projects and this is the reason for the change in `5.8.2` which unfortunately caused your issue as a side-effect.

**Comment by nagash77** [comment]
Hello, I just merged in @MikeMcC399 's PR and [5.8.3](https://github.com/cypress-io/github-action/releases/tag/v5.8.3) just released.  Please see if that fixes your problem.

**Comment by ghiscoding** [comment]
> @ghiscoding
> 
> I forked your repo and confirmed
> 
> 1. Changing your script name from `cypress` to `cypress:open` allowed `cypress-io/github-action@v5.8.2` to run successfully.
> 2. Without the script name change and after the merge of PR [revert: "fix: use yarn instead of npx with yarn.lock (#914)" #942](https://github.com/cypress-io/github-action/pull/942) `cypress-io/github-action@v5` picks upDownload action repository 'cypress-io/github-action@v5' (SHA:d69252d52b9a31bad4f418f05ba2bc83687a02eb) aka [v5.8.3](https://github.com/cypress-io/github-action/releases/tag/v5.8.3) which also runs successfully.

Thanks for all the troubleshooting, this is really helpful and I was quite surprise that the npm script name could affect this github action, I just started my day I'm in the process of updating everything with a PR running on my end.

So I can confirm that v5.8.3 works for me. Thanks a lot for the quick response

**Comment by ssay-work** [comment]
Thanks all, the reason `5.8.2` was failing for us is the exact same reason that @MikeMcC399 discovered for @ghiscoding . 

I'll bring up the documentation to my devs, and we'll look at changing that script name from `cypress` to `cypress:open`. 

Appreciate the quick turnaround on this!

**Comment by MikeMcC399** [comment]
There is now a caution published to the Cypress documentation

 [Getting Started > Opening the App > Adding npm Scripts](https://docs.cypress.io/guides/getting-started/opening-the-app#Adding-npm-Scripts)

which explicitly advises against using `cypress` as the name of a script, due to its unwanted side-effects in a Yarn environment.
