### ISSUE TITLE
Github Action Cypress run with i18n works locally but not in Github Action

### ISSUE THREAD

**Issue by darrylsepeda** [cypress-io/github-action#956]
So I have one test case look like this:

```
it('Show translation based on the language', () => {
    cy.window().should('have.property', 'store');
    cy.window()
      .its('store')
      .invoke(
        'dispatch',
        setConfig({
          lang: 'de-DE'
        })
      );
    mount(renderWithIntl(<Component />));
  });
  it('Shows translation fr', () => {
    i18n.changeLanguage('fr-fr');
    cy.window().should('have.property', 'store');
    cy.window()
      .its('store')
      .invoke(
        'dispatch',
        setConfig({
          lang: 'fr-FR'
        })
      )
      .then(() => {
        mount(renderWithIntl(<Component />));
        cy.get('[data-testid="title"]', { timeout: 20000 })
          .should('be.visible')
          .should('have.text', 'Sélectionner');
      });
  });
```

The second block successfully works in local, but always failed in Github Action with this error message:

```
Timed out retrying after 20000ms
      + expected - actual

      -'Select'
      +'Sélectionner'
```

Any insight why it works fine in local, but always failed in Github Action?

here are my versions:
- "cypress": "12.14.0"
- cypress-io/github-action@v5
- "react-i18next": "11.17.2",
- "i18next": "21.8.10",

**Comment by MikeMcC399** [comment]
@darrylsepeda 

It's unlikely that the problem is directly caused by `github-action`. More likely would be differences in timing running in a GitHub runner compared to running locally.

What is your `*.yml` workflow?

You may also want to consider tapping into the know-how available within the Cypress technical community on Discord, and ask for their advice.

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)

**Comment by nagash77** [comment]
I agree with @MikeMcC399 's assessment.  Can you share your workflow file as well as a [repo demonstrating the problem](https://github.com/nagash77/cypress-test-tiny) with the full test?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
